use DB_Programming

-------FLOW STATEMENTS--------
--WHILE LOOP
DECLARE @Count INT;
Set @Count=1
WHILE @Count<=5
BEGIN
    PRINT @Count;
	SET @Count=@Count+1
END
PRINT 'END OF LOOP'
-------------------------------
DECLARE @NUM1 INT;
DECLARE @NUM2 INT;
SET @NUM1=9
SET @NUM2=1
WHILE @NUM2<=10
BEGIN
    PRINT CONCAT(@NUM1,'X',@NUM2,'=',@NUM1*@NUM2)
	SET @NUM1=@NUM1
	SET @NUM2=@NUM2+1
END
PRINT 'END OF LOOP'
--NESTED LOOPS
DECLARE @TABLENO INT;
SET @TABLENO=1
WHILE @TABLENO<=10
BEGIN
    DECLARE @INNERCOUNT INT = 1;
	WHILE @INNERCOUNT<=10
		BEGIN
		  PRINT CONCAT(@TABLENO , 'X' , @INNERCOUNT,' = ',@TABLENO*@INNERCOUNT)
		  SET @INNERCOUNT=@INNERCOUNT+1
		END
	SET @TABLENO=@TABLENO+1
END
PRINT 'END OF LOOP'
--