use DB_Programming

----------HOW TO EXECUTE STORED PROCEDURES-------------
SELECT * FROM tbl_EmployeeDetails
--CREATE 
CREATE PROC spDEPARTMENT
AS
BEGIN
SELECT *FROM tbl_EmployeeDetails WHERE Emp_Department = 'Security'
END
--ALTER
ALTER PROC spDEPARTMENT
AS
BEGIN
SELECT *FROM tbl_EmployeeDetails WHERE Emp_Department = 'Security'
SELECT *FROM tbl_EmployeeDetails WHERE Emp_Department = 'HR'
END
--DROP
DROP PROC spDEPARTMENT2
--BY GIVING PARAMETERS
CREATE PROC spDEPARTMENT2
@emp_dept VARCHAR(100) ,
@emp_age decimal(2) 
AS
BEGIN
SELECT *FROM tbl_EmployeeDetails WHERE Emp_Department = @emp_dept
SELECT *FROM tbl_EmployeeDetails WHERE Emp_AGE = @emp_age
END

EXEC spDEPARTMENT

EXEC spDEPARTMENT2 'HR',20

--OUTPUT PARAMETERS
CREATE PROC spADDNo
@Num1 INT,
@Num2 INT,
@Result INT OUTPUT
AS
BEGIN
   SET @Result=@Num1+@Num2
END
--VARIABLE TO STORE VALUE
DECLARE @RES INT
EXEC spADDNo 4,5,@RES OUTPUT
SELECT @RES

--COMMAND TO GET STORED PROCEDURE
sp_helptext spADDNo

--TO ENCRYPT STORED PROC
CREATE PROC spADDNo2
@Num1 INT,
@Num2 INT,
@Result INT OUTPUT
WITH ENCRYPTION
AS
BEGIN
   SET @Result=@Num1+@Num2
END
--VARIABLE TO STORE VALUE
DECLARE @RES INT
EXEC spADDNo2 4,5,@RES OUTPUT
SELECT @RES
--COMMAND TO GET STORED PROCEDURE
sp_helptext spADDNo2
--CURSORS
DECLARE
@ROLLNO INT ,
@NAME VARCHAR (100) ,
@CLASS VARCHAR (10) ,
@ENGLISH INT  ,
@MATHS INT  ,
@SCIENCE INT  
DECLARE 
@TOTAL_MARKS INT, 
@PERCENTAGE INT

DECLARE student_cursors CURSOR FOR SELECT ROLLNO,[NAME],CLASS,ENGLISH,MATHS,SCIENCE
FROM STUDENT_MARKS;

OPEN student_cursors;

FETCH NEXT FROM student_cursors INTO @ROLLNO, @NAME, @CLASS, @ENGLISH, @MATHS, @SCIENCE

WHILE @@FETCH_STATUS=00
BEGIN
     PRINT CONCAT ('ROLLNO:',@ROLLNO);
	 PRINT CONCAT ('NAME:',@NAME);
	 PRINT CONCAT ('CLASS:',@CLASS);
	 PRINT CONCAT ('ENGLISH:',@ENGLISH);
	 PRINT CONCAT ('MATHS:',@MATHS);
	 PRINT CONCAT ('SCIENCE:',@SCIENCE);

	 SET @TOTAL_MARKS = @ENGLISH + @MATHS + @SCIENCE
	 PRINT CONCAT ('TOTAL MARKS :',@TOTAL_MARKS)

	 SET @PERCENTAGE=@TOTAL_MARKS/3;
	  SET @PERCENTAGE=@TOTAL_MARKS/3;
	 PRINT CONCAT('PERCENTAGE :',@PERCENTAGE , ' % ')
	 IF @PERCENTAGE >90
	   BEGIN
	        PRINT 'GRADE : A';
	   END
	   ELSE IF @PERCENTAGE >80 AND @PERCENTAGE <90
	   BEGIN
	        PRINT 'GRADE : B';
	   END
	   ELSE IF @PERCENTAGE >70 AND @PERCENTAGE <800
	   BEGIN
	        PRINT 'GRADE : C';
	   END
	   ELSE  
	   BEGIN
	        PRINT 'GRADE : D';
	   END
	   PRINT'========================'
	   FETCH NEXT FROM student_cursors INTO @ROLLNO, @NAME, @CLASS, @ENGLISH, @MATHS, @SCIENCE
END
CLOSE student_cursors;
DEALLOCATE student_cursors;
	   
	   